version: '3'

services:
  api:
    build:
      context: ../..
      dockerfile: backend/infrastructure/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    build:
      context: ../..
      dockerfile: backend/infrastructure/Dockerfile.worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    deploy:
      replicas: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
